### ISSUE TITLE
Attributes hidden behind data() method - problematic?

### ISSUE THREAD

**Issue by tkambler** [marmelab/restful.js#12]
Thanks for working on this. An alternative to Restangular that is framework-agnostic is desperately needed. :)

The fact that entity attributes are hidden behind a `data()` method seems problematic to me. When using Restangular, I'll often do something like this:

```
Restangular.all('users').getAll().then(function(users) {
	$scope.users = users;
});
```

Then, in the template, I can directly iterate over the result set and access attributes, etc..., like so:

```
<ul>
	<li ng-repeat="user in users" ng-bind="username"></li>
</ul>
```

Granted, this isn't designed *for* Angular, but the use case remains. For instance, right now I'd like to take the result from a collection call and dump it directly into a Knockout observable array, which my template can then iterate through via `data-bind="foreach: ...`

**Comment by RobinBressan** [comment]
Hi,
Thanks for your feedback.

Can't you do it with a `map`?

```js
$scope.users = users.map(function(user) {
    return user.data();
});
```

**Comment by tkambler** [comment]
I could (and am at the moment) - but hiding these attributes behind `data()` forces me to do this *each* time I want to reference an entity / collection within a template - and I do that *frequently.* Is there an argument for *not* making them directly available as properties, as Restangular does?

**Comment by fzaninotto** [comment]
The problem with Restangular is that it mixes the attributes (from the response) and the REST methods (from the library) in the same object, resulting in data loss (cf https://github.com/marmelab/ng-admin/issues/273). It's a design choice to be explicit by default, and we chose to expose chaining methods first, and data second. But maybe we should expose data first, and chaining methods second?

**Comment by stupidisum** [comment]
Maybe you can give an option for result type: `chaining method` or `data`, both globally and locally( for single-request).

```
const articleMember = api.one('articles', 1);  // http://api.example.com/articles/1

const api = restful('http://api.example.com', requestBackend(request), {dataFirst: true});

articleMember.get({dataFirst: false}).then((response) => {
    const articleEntity = response.body();

    const article = articleEntity.data();
    console.log(article.title); // hello, world!
});

articleMember.get().then((response) => {
    const article = response.body();
    console.log(article.title); // hello, world!
    article.__someSpecialName__.all('authors').getAll();
});


```
