### ISSUE TITLE
Use restful.js in isomorphic web application.

### ISSUE THREAD

**Issue by meric** [marmelab/restful.js#17]
I wanted to use restful.js on both server and browser to connect to 3rd party REST API. With generic npm install restful.js, I couldn't get it to run on the server, node complains the global "navigator" (amongst others) couldn't be found. 

I didn't need a minified version of restful.js because we could just `require(restful.js)` and our gulp/browserify toolchain will take care of concating and minifying it. 

I haven't made a pull request because I suspect you *really* don't like relative imports, which I needed so I didn't have to prepend NODE_PATH=<some value> on all our server start scripts, anyways I'll link to the comparison page:
https://github.com/marmelab/restful.js/compare/master...GradConnection:master

With these changes, `npm install GradConnection/restful.js`, and the use of `require` and our gulp + browserify build process, it works on the node server and browser with no other configuration required.

But I've probably broken it for webpack.

**Comment by RobinBressan** [comment]
Hello,

I use the relative imports for two reasons:
* I can move the code anywhere in the project, the imports still work.
* I have an explicit path to read. Just my opinion but I think it is much better to read  `model/collection` than only `./collection`.

About the `navigator`, maybe we should provide two compiled files. One for the browser and one for node (unless webpack can already handle this case).

**Comment by meric** [comment]
I like the imports too except I couldn't get node to recognise it besides using NODE_PATH.

I am not that experienced with webpack. Good idea with providing two compiled files. It might mean the require path has to be different on server and client but IMO it's pragmatic enough compromise to keep the library easy to use with minimal setup.

**Comment by sebas5384** [comment]
Can I use Restful.js (latest version) in node and in the browser through webpack ?

**Comment by RobinBressan** [comment]
@sebas5384 Will be fixed by #50
