### ISSUE TITLE
API difference with the README ?

### ISSUE THREAD

**Issue by aurels** [marmelab/restful.js#18]
I've just tried the library, it seems to be really simple and powerful ;-)

In the README, it's said to use `response.body()` and `response.data()`. But when I do a `getAll`, the *response* I get is a *function* and not an *object*.

After digging, this code works for me : 

    backend.all('artists.json').getAll().then(function(response){
      self.setState({
        artists: response().data.artists
      });
    });

So I have to call `response()` but not `data`. Right ? Am I doing something wrong ?

Thanks

**Comment by RobinBressan** [comment]
Hi,

Indeed the both work ! The recommended way is to use the API described in the README. Almost everything is a function in the lib. I use this pattern to encapsulate the various abstractions. So if you do: 
 `restful('api.example.com')()()()` you can retrieve the fondation which is `axios`.

**Comment by aurels** [comment]
Hi,

Mmm, if I `console.log` the *response* I get `function (){return t}`. So the only thing I can do is calling it, how can it have methods on a function ? `response.data` is `undefined`.

Thanks

**Comment by RobinBressan** [comment]
Try with a : `Object.getOwnPropertyNames(response)`. You'll see the methods. JavaScript allows us to add properties and method on function, it is used in functional programming (but not doing some here).

**Comment by aurels** [comment]
Indeed, this works : 

    backend.all('artists.json').getAll().then(function(response){
      console.log(Object.getOwnPropertyNames(response));

      self.setState({
        artists: response.body().data().artists
      });
    });

My bad ;-)
