### ISSUE TITLE
Rails gem for restful.js

### ISSUE THREAD

**Issue by aurels** [marmelab/restful.js#19]
Hi,

I don't know what you use server side, but I use Rails. So I made this tiny gem to embed `restful.js` easily in the asset pipeline of any Rails project (standard way) : 

+ GitHub : https://github.com/aurels/restfuljs-rails
+ RubyGems : https://rubygems.org/gems/restfuljs-rails

Please give me your feedback about that. Thanks!

**Comment by RobinBressan** [comment]
Hi,

I am not very familiar with Rails as I don't use ruby. But well done! Maybe you should update the README to remove the `momentjs` mention.

And I saw that `restful` is committed. How the gem handles update of the lib?

**Comment by aurels** [comment]
Hi,

Oops, the `momentjs` gem was my main inspiration ;-)

Yes your dist code is part of the repo. I plan to mirror your versions. I was thinking of a task to create the new version. Do you think there is a better way?

**Comment by jpetitcolas** [comment]
Not sure about a correct way to mirror the repo. Perhaps using a cron and the [tags ATOM feed](https://github.com/marmelab/restful.js/tags.atom)? Or, more manually, just following this RSS to detect when a new version is available?

Closing this issue, as it sounds more a restfuljs-rails issue now. :)

**Comment by aurels** [comment]
Hi,

I have a recipe in IFTTT watching the ATOM field so I get an email when a new version is released ;-)
