### ISSUE TITLE
restful.min.js gives compilation error

### ISSUE THREAD

**Issue by ospi** [marmelab/restful.js#20]
The first line in restful.js/dist/restful.min.js:

```javascript
!function(t,e){"object"==typeof exports&&"object"==typeof module?module.exports=e():   .....
```
gives the following compilation error trying to run restful.min.js in Play Framework:
*"Expected an assignment or function call and instead saw an expression."*

Is the js-file packaged correctly? I included the js-file as described:
```
<script type="text/javascript" src="javascripts/restful.min.js"></script>
```

**Comment by RobinBressan** [comment]
Hi,

I've tried both master and 0.6.1 minified files and it works. Is it executed in a browser ? Or in a Java like one (because of the Play Framework) ?

**Comment by ospi** [comment]
It worked fine, when putting the file directly into the public folder, instead of the asset folder. Play Framework seems to be a bit stricter during compilation of the js-file.

Thank you for your quick response!

**Comment by ospi** [comment]
From the Play Framework documentation (https://www.playframework.com/documentation/2.3.x/AssetsJSHint): 
"Any JavaScript file present in app/assets will be processed by JSHint and checked for errors."

Try running JSHint to reproduce compilation errors.

**Comment by jpetitcolas** [comment]
Just added JSHint. It should be fine during the next rebuild.
