### ISSUE TITLE
Make id param optional

### ISSUE THREAD

**Issue by umidbekkarimov** [marmelab/restful.js#21]
Thanks for great work, but there is some tiny issue here

I have some methods in api that doesn't requre `id` field (like sessions)
so this -> `Session.get()`
generates this -> `/api/v1/auth/undefined`

So i have to use `Session.getAll()` method, which is not quite properly.

**Comment by RobinBressan** [comment]
Hi,

Indeed I did not think about this use case. We should expose a method for that. In the meantime, maybe you can do a `Session.get('')` and when you get the response do a `response.body(false)` to get back the raw data and not an entity.

**Comment by kevin-smets** [comment]
:+1: for picking it up and :+1: for the workaround :).

**Comment by borgand** [comment]
This would be very nice.

The workaround does not work for me (using Laravel 5 for backend) as that still produces URLs like `/api/current_user/` (note the trailing slash) and that route does not exist in the backend.

Instead I defined a method `singleton()` that aliases `getAll()` to `get()`

    api.singleton = function(url){
      var s = this.all(url)
      s.get = s.getAll
      return s
    }

Usage

    currentUser = api.singleton('current_user')
    currentUser.get()   // resulting URL: /api/current_user


Perhaps you could implement this method?

**Comment by RobinBressan** [comment]
Hi,

Have you try this https://github.com/marmelab/restful.js#custom-endpoint-url ?

**Comment by borgand** [comment]
Thanks, custom URLs might solve my problem with slashes.

But still - omitting `id` from the arguments should not append `undefined` to the URL, but leave it as is.

**Comment by RobinBressan** [comment]
@borgand #50 will expose a simpler api and the `custom` method will do the job.
