### ISSUE TITLE
Allow PUT requests send query params

### ISSUE THREAD

**Issue by umidbekkarimov** [marmelab/restful.js#22]
Currently i am migrating from angular to react,
Angular `$resource` has an option to send query params via PUT requests,

So i could handle methods like: `PUT /api/v1/task/1?status=1`

**Comment by RobinBressan** [comment]
Sorry for the delay. It is not currently possible, but should be easy to add. Leaving the issue open to not forget it.

**Comment by Raffo** [comment]
The support for query parameter is missing for any method, not only for PUT requests, isn't it?

**Comment by jeromemacias** [comment]
Yes, all except the `get` method, we need to pass optionnal query parameters in all methods.

**Comment by RobinBressan** [comment]
@Raffo Will be fixed by #50
