### ISSUE TITLE
Dealing with collections?

### ISSUE THREAD

**Issue by anyong** [marmelab/restful.js#23]
So I'm coming from Restangular and trying to use restful.js now, and I've noticed some really odd behavior. When I get a collection via api.all(endpoint).getAll().then(...), my response is an array of functions rather than objects with functions on them. If I pull something out of this array with `response.body()[0].data()`, then I've lost all of the functionality for the entity convenience methods, but if I just keep `response.body()` then I've got no way to use this data directly in any normal data structure.

Are there any plans to do things the Restangular way (or have an option for it) by extending Array with the response body for collections, and then adding on the convenience methods to the collection (and each element)? I'd like to be able to do:

```js
api.all(endpoint).getAll().then( function(response) {
    var el = response[0] // here is the data at response[0], some JSON object {name: , date: ...}
    el.name = "john";
    el.save
    dataGrid = response; // dataGrid expects Array of JSON objects
}
```

And so on. Am I missing something, or is this currently not possible with restful.js?

**Comment by fzaninotto** [comment]
ping @RobinBressan

**Comment by RobinBressan** [comment]
Hi,

I am not sure to really understand what you want to do. But if you are looking way to retrieve only the raw body, you can get it by calling `response.body(false)`.

Does this answer your question?

**Comment by anyong** [comment]
Ok, maybe I didn't explain it clearly. Here's some code:

```js
function getList (endpoint, params) {  
  return api
    .all(endpoint)
    .getAll(params)
    .then(function(response) {
      var data = response.body();
      console.log(data); // [function, function, function, ...]
      console.log(data[0].data());  // the data I want
      return data;  // this data is not usable on the outside
    })
    .catch((error) => {
      console.log(error);
    });
}

fillMyTable function() {
    var tableData = [];
    getList('books', {search: 'Ernest Hemingway'}).then((data) => {
        tableData = data; // doesn't work because data === [function, function, function, ...]
        tableData = data.map(function(item) {
            return item.data(); // seems silly to have to do this and...
        })
        console.log(tableData[0]); // i've lost the convenience methods, anyway! (.save(), .remove(), etc.)
    });
}

// In restangular:

fillMyTable function() {
    var tableData = [];
    getList('books', {search: 'Ernest Hemingway'}).then((data) => {
        tableData = data;
        console.log(tableData[0]); // the convenience methods are all attached to the object so i can use that object and call .save() or .delete() from anywhere...
    });
}
```

Thanks!

**Comment by anyong** [comment]
Ok I was just playing around with the code and this is getting somewhere but I can't get the tests to pass yet. For three of the tests you can simply remove the call to `.data()` as that's no longer necessary, but I'm not sure why the functions are not getting saved correctly like this:

```js
// entity.js
// remove data() from var model = { ..., data() }, and add this:

    for (var func in model) {
      if (model.hasOwnProperty(func)) {
        Object.defineProperty(data, func, {
          value: model[func]
        });
      }
    }

return data;
```

**Comment by tomaash** [comment]
@RobinBressan, I'd +1 this issue. @anyong did not do a good job explaining it more, it rather became more obfuscated. But it's simple. response().data of getAll is an array of plain objects without convenience methods. We would like to have those methods (like save()) on those objects as well. Is that possible? And if not, what is the correct way to conveniently modify and save an object that was fetched using getAll?

**Comment by anyong** [comment]
@tomaash sorry for my crappy explanation, but thanks for making it more concise - that's exactly what I mean. :+1:

**Comment by RobinBressan** [comment]
Hi,

Sorry for the delay. Indeed it is clearer now. It is not possible because when you do a `getAll` restful considers the response as an array of entities and not an unique entity. So right now the only way is to fetch a member (url like `/xxxx/:id`) with `get` which will returns an array.

**Comment by tomaash** [comment]
Hmm, maybe there's some deeper issue. Is the readme outdated? I cannot find out how to actually call save on anything. In readme, there's written that you can do:
```javascript
api.one('articles', 1).get().then(function(response) {
    var articleEntity = response.body();

    // if the server response was { id: 1, title: 'test', body: 'hello' }
    var article = articleEntity.data();
    article.title = 'test2';
    // Finally you can easily update it or delete it
    articleEntity.save(); // will perform a PUT request
```
but for me, response is a function:
```javascript
api.one('articles', 1).get().then(function(response) {
    var articleEntity = response().data;
```
and data is always plain object. On response(), there's also config, headers, status, statusText and that's all. Am I doing something wrong? In any case, the documentation does not seem to be up to date with v0.6.1 I'm using.

**Comment by RobinBressan** [comment]
Hello,

Sorry again for the delay, I don't have much time these days. `response` is indeed a function because in restful, abstractions are isolated into closures. But it still exposes the method described in the README.

See https://github.com/marmelab/restful.js/issues/18

**Comment by RobinBressan** [comment]
@tomaash #50 will fix this. The code is now much simpler.
