### ISSUE TITLE
Is there a top level Error Handler

### ISSUE THREAD

**Issue by raygerami** [marmelab/restful.js#24]
Hi, 
I would like to capture and handle any 401 errors received from server using resfuljs in a sort of global way.
I know we can call the api and use .capture of the promise to capture individual calls errors, but  I thought may be there is a way to do this in a central manner, instead of having the same error check cone in all api calls.
Thanks

**Comment by RobinBressan** [comment]
Hi,

Have you try to use interceptors to check for any errors? If it does not work, maybe [axios](https://github.com/mzabriskie/axios) provides a way to do it.

**Comment by rbarilani** [comment]
+1

**Comment by RobinBressan** [comment]
@raygerami #50 will bring error interceptors and events and it should fix your issue.
