### ISSUE TITLE
IE8 support

### ISSUE THREAD

**Issue by thr0wabl3** [marmelab/restful.js#27]
Awesome library, but couldn't find anything on browser support in docs. Should it run in IE8?

**Comment by keradus** [comment]
Yeah, it would be great to know that!
Any news on that ?

**Comment by RobinBressan** [comment]
We did not test the library in different browsers. The last release use modern javascript and native promise. You could try it with some polyfills like the one advised for native promise into the README: https://github.com/jakearchibald/es6-promise.
