### ISSUE TITLE
Request Interceptors fire after request?

### ISSUE THREAD

**Issue by opengeek** [marmelab/restful.js#33]
I'm trying to use a Request Interceptor to get a new access token if the expiration time as passed and update the Authorization header of my request before it is sent. However, it appears that the interceptors fire after the request, which is fairly useless. At that point I'd want a response interceptor, but it seems a request interceptor should fire before the request. Am I missing the point?

**Comment by RobinBressan** [comment]
@opengeek #50 brings a full rewrite of interceptors engine and should fix this when merged.

**Comment by opengeek** [comment]
thanks for the update
