### ISSUE TITLE
Multiple query string values encoding problem

### ISSUE THREAD

**Issue by bkotyik** [marmelab/restful.js#34]
Hello,
I would like to have a query param multiple times to appear in the query string with different values.
I use apii.all('users').getAll({filter: ["name;like;Mobil'", "name;like;Walter"]]}) and I think It doesnt work as it should:

The expected result is that it invokes GET "http://myurl.com/users?filter=name;like;Mobil&filter=name;like;Walter".

Instead of this, the lib requests the "http://myurl.com/users?filter=%5B"name%3Blike%3BMobil"%5D&filter=%5B"name%3Blike%3BWalter"%5D".

So It force encodes the content of the array, but it should not.

**Comment by RobinBressan** [comment]
Hi, we've just released a new version of restful.js. The http backend is no longer the same. You should give it a try and check if your issue is still here.

**Comment by liuq** [comment]
Hi, I am using the new restful.js version (0.9.1), however the problem is even worse: it seems that the params argument of getAll is completely ignored.

The snippet of the code is the following:

api.all('instances').getAll({ fields: ['name', 'file_size' ] }), which simply creates the url
http://myurl.com/instances

**Comment by RobinBressan** [comment]
Hi,

Thank you for your answer. Do you use request or fetch?

**Comment by liuq** [comment]
Hi,
I am using fetch (on the client side).

**Comment by RobinBressan** [comment]
Ok, I've just seen that fetch does not support a params config... We must add them manually in the url in the fetch http backend. I will write a fix.

**Comment by liuq** [comment]
Great!
