### ISSUE TITLE
Npm installs not the latest version

### ISSUE THREAD

**Issue by bkotyik** [marmelab/restful.js#35]
The codebase that can be downloaded via npm is not the same that is in the repository.
Although the version in the package.json is the same of both, the instance that installs via npm is lack of "allUrl" and "oneUrl" methods.

**Comment by jpetitcolas** [comment]
We just published a `0.6.2` version embedding all latest changes, including `allUrl` and `oneUrl`. It should then be available on your project. Feel free to re-open this issue if it still doesn't work. :)

**Comment by bkotyik** [comment]
BUMP: There is a wrong version in NPM again. The version can be found here in the GIT repo is 0.6.2.
If I install from NPM it gets the version 0.7.0 (how?) which doesnt include the fix I pulled a month ago.
