### ISSUE TITLE
Axios should be a dependecy, not bundled in

### ISSUE THREAD

**Issue by nathanboktae** [marmelab/restful.js#42]
Bundling Axios in your library rather than depending on the package is bad form - users can't use axios directly for non-rest reasons, and have to wait for you to release a new version to take patch and minor bumps of axios.

Imagine if I had a server with some non-rest endpoints, I'd have to have 2 ajax clients and potentially configure them with the same auth / CSRF setup. Quite painful.

**Comment by nathanboktae** [comment]
This can be fixed by using a UMD wrapper, and detecting AMD / CommonJS / ES6 loaders. Not sure how that works with your webpack / es6 build setup you have though...

**Comment by RobinBressan** [comment]
@nathanboktae #50 rewrites the http layer and allow several http backend. This should be solved when merged.
