### ISSUE TITLE
Any put and post example with data in request?

### ISSUE THREAD

**Issue by dkim-hgs** [marmelab/restful.js#43]
I'm trying to call rest back end which is get, put and post. 
I tested get with back end and it works as expected. but i'm keep getting  No 'Access-Control-Allow-Origin' header is present on the requested resource error when using put and post.
Do you have any example to use put and post in detail?

**Comment by RobinBressan** [comment]
You must configure your server to expose CORS headers if you query your api from another domain.

**Comment by RobinBressan** [comment]
No feedback on this and it is a server side issue and not a restful one. Closing.
