### ISSUE TITLE
Distribute a non-minified version too

### ISSUE THREAD

**Issue by greelgorke** [marmelab/restful.js#44]
please, put a non-minified version of the build into the dist too.

**Comment by xiaomin-em** [comment]
i need a non-minified version too. thanks!

**Comment by nd2s** [comment]
+1

**Comment by flyfishMT** [comment]
+1

**Comment by suricactus** [comment]
+1

**Comment by RobinBressan** [comment]
@greelgorke #50 will add unminified files when merged.
