### ISSUE TITLE
restful can't work without parameter

### ISSUE THREAD

**Issue by kadkaz** [marmelab/restful.js#45]
When I create 
{code}
var api = restful();
{code}

I expect to use current url from website. 
if the website deployed to localhost then expect http://localhost/
if the website deployed to api.company.com then http://api.company.com.
it should not be mandatory.

Right now I have:
http://undefined/

**Comment by JoshZA** [comment]
:+1:

**Comment by RobinBressan** [comment]
@kadkaz #50 will fix this when it is merged.
