### ISSUE TITLE
multipart/form-data for file uploads

### ISSUE THREAD

**Issue by vitosamson** [marmelab/restful.js#46]
Can restful.js handle multipart data? Here's what I've tried which does not work:

```
var baseApi = restful(config.API_HOST)
            .header('Authorization', 'Bearer ' + token)
            .prefixUrl(config.API_PREFIX)
            .port(config.API_PORT);

function uploadFile(assetId, upload) {
  var data = new FormData();

  data.append('file', upload.file); // upload.file is a File instance
  data.append('name', upload.name);

  return baseApi
        // .header('Content-Type', 'multipart/form-data') // why doesn't this override the default application/json header?
        .addRequestInterceptor(function(data, headers) {
          headers['Content-Type'] = 'multipart/form-data';
          return data;
        })
        .one('assets', assetId)
        .all('files')
        .post(data); // also tried passing `upload` directly
}
```

Passing the `upload` object sends in a JSON payload of `{file: {}, name: 'foo'}`, while passing the FormData object sends an empty JSON object.

I can't find anything in the docs about this.

**Comment by vitosamson** [comment]
Seems like this was an issue in axios that was resolved in 0.5.4 - https://github.com/mzabriskie/axios/commit/42fc3954d2acd0d9366afa03dd0add0fbe44d42c

Any idea when we can expect restful.js to bump axios to 0.5.4?

**Comment by vitosamson** [comment]
Actually even with axios@0.5.4, restful.js tries to `JSON.stringify` the data in its default request interceptor here: https://github.com/marmelab/restful.js/blob/693f9138bcb7e5de944fb4c468bd388ad80d49fc/src/service/http.js#L17

There should be some checks before doing that. I can try to whip up a PR for that.

**Comment by RobinBressan** [comment]
@vitosamson #50 rewrites restful and should fix this.
