### ISSUE TITLE
Bluebird promises (or the possibility to use a custom promises framework)

### ISSUE THREAD

**Issue by andresmatasuarez** [marmelab/restful.js#57]
It would be great if `restful.js` offered a way to work with different promises frameworks. In particular, I use `Bluebird` a lot and find most of the tools it offers essential to my projects, i.e, `.finally` just to name one.

I think it would be awesome if I can take advantage of the declarative approach of `restful` together with the power of `Bluebird` (or the promise framework you prefer).

I known I can `Bluebird.resolve` the resulting `restful` promise, but I don't want to perform that wrapping manually every time I needed to.

What do you think?

**Comment by RobinBressan** [comment]
I disagree with you. I had to remove the es6 promise polyfill from restful.js for the same reason. We should not provide a way to use different Promise implementation, it is not the responsibility of the lib. restful.js uses the native one in JavaScript and therefore if you want to use different promise framework you must do it on your own.

More globally, restful.js is about micro-service lib and we should try to keep it small. And the best way to do so is to use native Promise in this case.

**Comment by andresmatasuarez** [comment]
I'm not necessarily saying that the lib should include any promise implementation framework. I am just thinking that maybe one could set their preferred promise framework from a config param, or exposing a callback version of each method so anyone can promisify it later with its preferred framework. The lib could use the native promises implementation by default, but offer a way to override that behaviour.

Think about a project that uses `bluebird`, `then/promise` or even a developer's custom promise implementation. Having `restful` using its own kind of promises introduces potential bugs and mishappenings due to incompatibilities with the framework used by the project and so, the developer should take special consideration into knowing which promise methods are available to which returned promises.

**Comment by jpetitcolas** [comment]
> Having restful using its own kind of promises introduces potential bugs and mishappenings due to incompatibilities with the framework used by the project 

Restful use native JavaScript promises, ie without any framework. This is not a custom kind of promise: we have made this choice to ensure long term sustainability.

I also disagree to add a hook for setting an extra promise framework, as it would add some complexity to the code we actually don't need.

But, feel free to fork restful to implement Bluebird support. That's under MIT license after all. :)
