### ISSUE TITLE
errorCode global interceptor

### ISSUE THREAD

**Issue by JamieMcDonnell** [marmelab/restful.js#58]
Hi there,
thanks for the restful.js lib, I'm finding it very useful.

I have a question re. making a global interceptor for errors of different types.

I want to handle rest errors globally, consistently, but can not figure out how to using restful.js.

If I were using jquery's ajax methods, I would simply use:

	//set a global method to handle 500 errors with ajax calls

	$( document ).ajaxError(function(err) {
		console.log("error: ", err);
          bootbox.dialog({
			message: "Ajax request failed with a 500 error - ",
			className: "danger",
			buttons: {
				danger: {
				  label: "OK",
				  className: "btn-danger",
				  callback: plenty_admin.HELPER.hideLoadingOverlay
				}
			},
			 onEscape: plenty_admin.HELPER.hideLoadingOverlay,
			 callback: plenty_admin.HELPER.hideLoadingOverlay
		});
	});
	

Can you possibly provide a similar example for use with a pretty basic instanciation of restful.js?

Thanks so much!

Jamie

**Comment by RobinBressan** [comment]
Hi,

Did you try to add an error interceptor to your root endpoint? (see https://github.com/marmelab/restful.js#interceptors)

Furthermore if you just want to be notified about any error, you can listen on the `error` event on your root endpoint (see https://github.com/marmelab/restful.js#error-handling).

Regards

**Comment by JamieMcDonnell** [comment]
Hi Robin,
thanks for your reply, but I guess I can't make sense of your documentation - I have read it and tried to use it as guidance, but to no avail.

This is what I am trying so far, but it is not working for me:
plenty_admin.api = restful(plenty_admin.REST.URL);
plenty_admin.api.header("Authorization", store.get("basicAuth"));
plenty_admin.api.on('error', function(err){
	console.error("restful api error", err);
});

How can I set up that top level error event handler using the Restful.js lib?

Thanks again

Jamie

**Comment by RobinBressan** [comment]
Hi,

I've edited your answer to add js type on your code to make it more readable.

You seem doing it the right way. Do you have any additional logs from your console?
Can you paste the line of code making the http request with restful?
Does your API return valid HTTP status code?

Regards

**Comment by JamieMcDonnell** [comment]
Hi, thanks for the quick reply - from the console I get:

```javascript
Uncaught TypeError: plenty_admin.api.on is not a function
```
Which would suggest that plenty_admin.api is not ready yet., or doesn't directly support the event handler... any ideas?

This is before I even make a request - the error blocks the app from running. Without this, all requests return successfully with valid HTTP status codes.

Thanks

Jamie

**Comment by RobinBressan** [comment]
It looks like you are using an old version of restful.js. Which one do you
use? The documentation on master is for 0.9.x versions.
Le ven. 16 oct. 2015 à 18:18, JamieMcDonnell <notifications@github.com> a
écrit :

> Hi, thanks for the quick reply - from the console I get:
>
> Uncaught TypeError: plenty_admin.api.on is not a function
>
> Which would suggest that plenty_admin.api is not ready yet., or doesn't
> directly support the event handler... any ideas?
>
> This is before I even make a request - the error blocks the app from
> running. Without this, all requests return successfully with valid HTTP
> status codes.
>
> Thanks
>
> Jamie
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/marmelab/restful.js/issues/58#issuecomment-148758672>.
>
-- 
Robin Bressan

Consultant chez Marmelab

**Comment by JamieMcDonnell** [comment]
Hi Robin,
thanks for your reply and apologies for my delay in getting back to you.

I updated restful.js to the latest version which fixed the event handler
issue, but has now opened up a whole world of other problems for me due to
changes in how results are returned from the various requests I am making.

e.g. in the past I was able to use, for example:
plenty_admin.REST.templatePlanToFieldCrops = plenty_admin.api.all
<https://contactmonkey.com/api/v1/tracker?cm_session=d208b7cb-ab47-4f68-952b-7a2e7d39d3da&cm_type=link&cm_link=b7952d1a-ab9c-48cf-9733-e07b8bf83f1a&cm_destination=http://plenty_admin.api.all>
("plan/applyTemplatePlanToFieldCrops");
plenty_admin.REST.templatePlanToFieldCrops.post
<https://contactmonkey.com/api/v1/tracker?cm_session=d208b7cb-ab47-4f68-952b-7a2e7d39d3da&cm_type=link&cm_link=09017986-e399-4a7c-bb2f-714202df9702&cm_destination=http://plenty_admin.REST.templatePlanToFieldCrops.post>
(templatePlanApplicationDto)
.then(
function(response){
console.log("planManifestationResultsDto: ", response);
if(Array.isArray(response.body
<https://contactmonkey.com/api/v1/tracker?cm_session=d208b7cb-ab47-4f68-952b-7a2e7d39d3da&cm_type=link&cm_link=2e616a32-008e-41f6-bb73-19bf02f6f37b&cm_destination=http://response.body>
())){
var returnData = plenty_admin.REST.get_array_from_data(response.body
<https://contactmonkey.com/api/v1/tracker?cm_session=d208b7cb-ab47-4f68-952b-7a2e7d39d3da&cm_type=link&cm_link=53554413-4be0-4fd5-b470-69d3c317f76c&cm_destination=http://response.body>
());
}else{
var returnData = response.body
<https://contactmonkey.com/api/v1/tracker?cm_session=d208b7cb-ab47-4f68-952b-7a2e7d39d3da&cm_type=link&cm_link=8b844396-80a6-4d28-88df-721b414f8c17&cm_destination=http://response.body>();
//"NO DATA";
}
}

Now when I try to post I receive an error, "Uncaught Error: Expected array
as response, you should use one method for that"

but using plenty_admin.REST.templatePlanToFieldCrops = plenty_admin.api.
<https://contactmonkey.com/api/v1/tracker?cm_session=d208b7cb-ab47-4f68-952b-7a2e7d39d3da&cm_type=link&cm_link=1ac2c479-1e57-4dc3-be69-adacd77f559f&cm_destination=http://plenty_admin.api>
*one*("plan/applyTemplatePlanToFieldCrops");

forces the rest path to ".../undefined".

How can I perform a POST using ".one('xxx')" rather than ".all('xxx')" as I
was doing before? I am really struggling to understand your documentation
I'm afraid - some real-world examples would really help.

Thanks a lot for your ongoing help, much appreciated ;)

Jamie

**Comment by carldunham** [comment]
Just wanted to add that I am seeing the same thing. The `<collection>.post()` works great, but at the point of calling `.data()`, it fails because it is expecting an Array to be returned (actually checking for the `.all()` method). And as Jamie says, using `one()` doesn't really make sense, and requires an ID.

Hope that helps.

**Comment by GXZL** [comment]
First off, thanks for putting something like this together.  I have what I hope is a simple question:

I'm using restful.js 0.9.6 and I have the following two lines defined in a js file

var restful = require('restful.js');
var resource = restful('http://httpbin.org', 8080);

It bombs out on the 'var resource' line saying 'restful is not a function'   I see that restful is an Object but it has the default function of restful(baseUrl, httpBackend).  Why is it complaining that it thinks restful is a function?  Any assistance would be greatly appreciated.
