### ISSUE TITLE
How to integrate with vue.js resources?

### ISSUE THREAD

**Issue by auvipy** [marmelab/restful.js#61]
do i need to replace vuejs resource or can add this with vuejs resource? or vuejs resource component need to be re written with resfuljs?

**Comment by Doogiemuc** [comment]
Might be a personal opinion, but as far as I know vue-resource this more ore less replaces it.  You can choose either.  Vue-ruesource is of course a litte bit more integrated into VueJS.  But you should be fine making your REST requests with restful.js and then filling your vue component's "data" from the returned responses.
