### ISSUE TITLE
How to set withCredentials

### ISSUE THREAD

**Issue by luiso1979** [marmelab/restful.js#65]
In order to send cookies I need to set withCredentials=true, but I can't find where to set it.

**Comment by RobinBressan** [comment]
Hi,

You must use a request interceptor to add it to the config before the request is sent.

**Comment by passcod** [comment]
Alternatively you can force it on every request by overriding the http backend, e.g. with fetch:

```js
restful(this.URL, fetchBackend((input, init) => {
  init = init || {}
  init.credentials = 'include'
  return window.fetch(input, init)
}))
```
