### ISSUE TITLE
Firefox fetch issue

### ISSUE THREAD

**Issue by rkovacevic** [marmelab/restful.js#66]
I'm getting this error in FF, when sending requests:
```
TypeError: response.headers.forEach is not a function
Stack trace:
exports.default/</</<@webpack:///./~/restful.js/dist/es5/http/fetch.js?:30:17
```
I'm using webpack, and have fetch and es6-promise plugged in, like described here:
https://gist.github.com/Couto/b29676dd1ab8714a818f

Any ideas what the problem is?

**Comment by rkovacevic** [comment]
btw, console.dir(fetch) and console.dir(Promise) look ok, it seems that polyfills are working.

**Comment by yborunov** [comment]
I also have this problem, and it's fetch polyfilling problem which is now working as all or nothing as oppose to checking individual features available. `forEach` method unavailable in Firefox implementation of Headers interface for `Fetch API`.

**Comment by cubbuk** [comment]
I also have this problem, using restful 0.9.3.

**Comment by rudin** [comment]
Same problem here!

**Comment by rudin** [comment]
..this does it, for now...
"restful.js": "git://github.com/janeirodigital/restful.js",

Pull Request: https://github.com/marmelab/restful.js/pull/68

**Comment by yborunov** [comment]
@rudin `response.headers` is not an Array and never be it, it's Headers object. What if I need access headers how does it help me?

**Comment by yborunov** [comment]
I've posted a PR at `fetch` polyfill repo, that should solve this problem on polyfilling level.
Please support it there: https://github.com/github/fetch/pull/265

**Comment by RobinBressan** [comment]
@yborunov Which version of each do you use? I am not able to reproduce it.

**Comment by yborunov** [comment]
@RobinBressan 
Firefox v43.0.3
Restful.js v0.9.2
whatwg-fetch v0.10.0

**Comment by yborunov** [comment]
Problem is still occurring in FF v43.0.3 because it doesn't have `keys` method in Headers object :(

**Comment by Mouvedia** [comment]
@yborunov is right. That doesn't fix it.
