### ISSUE TITLE
Can't pass cookie along with request to api

### ISSUE THREAD

**Issue by yborunov** [marmelab/restful.js#67]
My API endpoint located at the same domain is required Cookies to be sent that contain authorization data. I've noticed that restful.js doesn't send cookie information with any request it make, therefore I've tried to manually add `Cookie` header using `api.header` method or pass it individually with `get` method or assign cookies header to specific collection but none of these attempts were successful.

Is there any issue related to the library or I do something wrong?

**Comment by yborunov** [comment]
I figured out that I have to enable `credential` option for `fetch` and also that the way to do it in `restful.js` is by passing 3rd parameter to endpoint methods, for example:
```
const api = restful('/api', fetchBackend(fetch))
const collection = api.all('resource', {}, {
  credentials: 'include'
})
```
What if I need to pass credentials to all my collections, wouldn't it be reasonable to add capability to pass this parameter to endpoint directly as follows:
```
const api = restfil('/api', fetchBackend(fetch))
api.config('credentials', 'include')
```

**Comment by yborunov** [comment]
Actually I was wrong, there's no way to pass cookie in restful.js so far

**Comment by CombatCode** [comment]
```
api.addRequestInterceptor(function(config) {
    config.credentials = 'same-origin';
    return config;
});
```

**Comment by yborunov** [comment]
Thanks, I've found this solution already. This issue may be closed.
