### ISSUE TITLE
Changelog and release notes

### ISSUE THREAD

**Issue by yborunov** [marmelab/restful.js#71]
I'd suggest to create `CHANGELOG.md` file and put a note in there once a new release happens.
From the recent [release 0.9.4](https://github.com/marmelab/restful.js/releases/tag/0.9.4), I believe it's worth being mentioned somewhere that `one` method [was removed](https://github.com/marmelab/restful.js/commit/2a11828dc17117c12cb1ae020ad3cf03f6becfbc#diff-9fe054eba8a4a0b8d0695bb4a3a46a67L48) from Collection endpoint. At least, might good to write it the release note. That's an important change for the patch version, as for me.

**Comment by RobinBressan** [comment]
Hi,

I've removed it because it wasn't supposed to be in Collection, that is the purpose of the `custom` method. Could you explain me in which case do you use it?

**Comment by yborunov** [comment]
Hi Robin,

This method was used for GET request to fetch posts' comments from following endpoint: `/posts/:id/comments` and implementation was `api.all('posts').one(id, 'comments').get()`
Now I had to replace it with: `api.one('posts', id).custom('comments').get()`

**Comment by yborunov** [comment]
And likely it'd been done wrong, since resource name was mixed up with id in `one` method, but more important here's to be aware of these kind of changes from a change log

**Comment by RobinBressan** [comment]
Indeed. It should be better to do:

api.one('posts', id).all('comments').getAll()

Anyway good point about the changelog :+1:
Le sam. 30 janv. 2016 à 17:35, Yuri Borunov <notifications@github.com> a
écrit :

> And likely it'd been done wrong, since resource name was mixed up with id
> in one method, but more important here's to be aware of these kind of
> changes from a change log
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/marmelab/restful.js/issues/71#issuecomment-177233467>.
>
-- 
Robin Bressan

Consultant chez Marmelab

**Comment by yborunov** [comment]
I'll do it this way from now on. Thanks for fixing firefox issue (that's the reason I'm upgrading, actually) and hope we'll see changelog in the next release.
