### ISSUE TITLE
Internet explorer then method doesn't trigger

### ISSUE THREAD

**Issue by lghiur** [marmelab/restful.js#74]
Hello,

I have tried to make a request to a custom endpoint and it works perfectly fine, except internet explorer, where the callback in "then" method is not executed. Do you guys have any idea on what might happen? Is this a know issue?

```
import 'whatwg-fetch';
import Restful, { fetchBackend } from 'restful.js';
require('es6-promise').polyfill();

var api  = Restful("http://localhost:4444", fetchBackend(fetch));

api.custom('highlights').get().then(() => {
   console.log('request done');
});
```

Thank you,
Laurentiu

**Comment by lghiur** [comment]
@RobinBressan do you have any idea about this?

**Comment by jpetitcolas** [comment]
@lghiur Have you tried [core-promise](https://github.com/bmustiata/core-promise/)?

**Comment by RobinBressan** [comment]
Hi!

Which version of internet explorer are you using? But it seems to be a polyfill issue, have you checked the es6-promise issues? https://github.com/jakearchibald/es6-promise/issues?utf8=%E2%9C%93&q=ie

**Comment by antalutrazvan** [comment]
The then method for the promise polyfill is triggered, but it cannot resolve, so it triggers the rejected callback with the error "Object does not have method keys" . It is from the whatwg-fetch polyfill,

If using fetch-polyfill, the error is "Object doesn't support this action".

**Comment by RobinBressan** [comment]
This seems related to #77. Have you tried with the last version of restful.js 0.9.5?

**Comment by lghiur** [comment]
@RobinBressan Thanks a lot, it works now!

**Comment by antalutrazvan** [comment]
@RobinBressan Thanks, 0.9.5 fixed it. Banging our heads over this all day.
