### ISSUE TITLE
get url

### ISSUE THREAD

**Issue by NikolayGalkin** [marmelab/restful.js#8]
Hi, I have a question. How can I get generated url from restful object. Is there a way to get from 

```js
var api = restful('api.example.com')
    .header('AuthToken', 'test') // set global header
    .prefixUrl('v1')
    .protocol('https')
    .port(8080);
```
the url: *https://api.example.com:8080/v1*

Maybe it would be good to add https://github.com/visionmedia/debug ?

**Comment by RobinBressan** [comment]
You should be able to call `api.url()` I think.

**Comment by NikolayGalkin** [comment]
thanks, you are right.
