### ISSUE TITLE
Is the es5 folder necessary ?

### ISSUE THREAD

**Issue by nolsherry** [marmelab/restful.js#89]
Hello @RobinBressan,
I am the member of [cdnjs](https://github.com/cdnjs) project.
We want to host this library.
I want to confirm whether the ```es5``` folder under ```dist``` is necessary ?
Thank you very much!

cdnjs/cdnjs#8425

**Comment by RobinBressan** [comment]
Hi, sorry for the delay. Yes it is necessary. The npm install targets this directory to be able to work on both es5 and es6 projects.

**Comment by RobinBressan** [comment]
Misunderstood your point sorry. You're right, for a CDN it is useless.

**Comment by nolsherry** [comment]
Thanks for your response.
